### ISSUE TITLE
Images rendering problem

### ISSUE THREAD

**Issue by jacubb** [tomaszwawrzyniakit/pimp-my-ford-web#1]
Hello, I have uploaded default untouched vbf version JS7T and got this issues with some images. Is it normal? What firmware version is supported? I am using this vbf file in my car and everything works fine, no issues with images at all.
![4bed5e4cb8d875716f76b32fd56d0ed4](https://user-images.githubusercontent.com/5689163/120508830-54e37380-c3c8-11eb-97fe-58284aca1d97.png)

**Comment by tomaszwawrzyniakit** [comment]
Hi, thanks for you ticket, there are 2 separate things:
1) IPC-Preview: Currently i have no idea how to decode masks encoded in RLE, so RLE images are visible but masks  for RLE bitmaps are broken
2) DDB-Preview: I want to standardize sizes for all tray bitmaps, (it is easier to use) and that's why "tray_digital_speedo" looks like this, Ford used here encoded file in different size than the other trays.  I can put there extra condition if "tray_digital_speedo" then use special, different than other trays resolution.

**Comment by tomaszwawrzyniakit** [comment]
Resolved, new version soon.
![image](https://user-images.githubusercontent.com/8846466/120730874-bef03b80-c4e2-11eb-8757-70be89ebfab4.png)
